let contact=new Array();let settings;let ends=[0,1,2,3,4,5,6,7,8,9];Number.prototype.format=function(n,x){var re='(\\d)(?=(\\d{'+(x||3)+'})+'+(n>0?'\\.':'$')+')';return this.toFixed(Math.max(0,~~n)).replace(new RegExp(re,'g'),'$1,');};(function(){function l(r){return null===r?"":encodeURIComponent(String(r).trim())}
function r(r,e){var t,a,o,s,i=[],n=!(!e||!e.lowerCase)&&!!e.lowerCase;if(null===r?a="":"object"==typeof r?(a="",e=r):a=r,e){if(e.path&&(a&&"/"===a[a.length-1]&&(a=a.slice(0,-1)),o=String(e.path).trim(),n&&(o=o.toLowerCase()),0===o.indexOf("/")?a+=o:a+="/"+o),e.queryParams){for(t in e.queryParams){if(e.queryParams.hasOwnProperty(t)&&void 0!==e.queryParams[t])
if(e.disableCSV&&Array.isArray(e.queryParams[t])&&e.queryParams[t].length)
for(var u=0;u<e.queryParams[t].length;u++)s=e.queryParams[t][u],i.push(t+"="+l(s));else s=n?e.queryParams[t].toLowerCase():e.queryParams[t],i.push(t+"="+l(s))}
a+="?"+i.join("&")}
e.hash&&(a+=n?"#"+String(e.hash).trim().toLowerCase():"#"+String(e.hash).trim())}
return a}
var e=this,t=e.buildUrl;r.noConflict=function(){return e.buildUrl=t,r},"undefined"!=typeof exports?("undefined"!=typeof module&&module.exports&&(exports=module.exports=r),exports.buildUrl=r):e.buildUrl=r}).call(this);let QuangApp=function(){initUrl=(queryParams)=>{return buildUrl("",{path:"api.php",queryParams})}
copyStringToClipboard=(str)=>{var el=document.createElement('textarea');el.value=str;el.setAttribute('readonly','');el.style={position:'absolute',left:'-9999px'};document.body.appendChild(el);el.select();document.execCommand('copy');document.body.removeChild(el);alert('ÄÃ£ sao chÃ©p sá»‘ Ä‘iá»‡n thoáº¡i nÃ y. ChÃºc báº¡n may máº¯n.');}
number_format=(number)=>{return parseInt(number).toLocaleString('it-IT',{style:'currency',currency:'VND'});}
initAjax=(data_ajax)=>{$.ajax(data_ajax);}
getNum=(remove)=>{let ends=[];for($i=0;$i<10;$i++){if(remove.indexOf($i)===-1){ends.push($i);};}
return ends;}
loadMomo=(ag)=>{initAjax({url:initUrl({type:"momo"}),method:"POST",success:function(data){if(data.status==true){let table_one="";let table_ten="<tr>";if(data.data_momo){let status_momo={0:`<span class="label label-info text-uppercase">Äang káº¿t ná»‘i</span>`,1:`<span class="label label-success text-uppercase">Hoáº¡t Ä‘á»™ng</span>`};let data_momos=data.data_momo;for(let momo of data.data_momo){var settings=JSON.parse(momo.settings);if(settings.transfers_today==undefined){settings.transfers_today={times:0,amount:0};}
table_one+=`<tr>`;table_one+=`<td>${momo.username} <span class="label label-success text-uppercase" onclick="QuangApp.coppy('${momo.username}')"><i class="fa fa-clipboard" aria-hidden="true"></i></span> <span class="label label-success text-uppercase" onclick="QuangApp.play('${momo.username}')"><i class="fa fa-play" aria-hidden="true"></i></span></td>`;table_one+=`<td>${status_momo[momo.status]}</td>`;table_one+=`<td><strong><span class="text-danger">${settings.transfers_today.times}</span> Láº§n</strong></td>`;table_one+=`<td><strong><span class="text-danger cash-format">${number_format(settings.transfers_today.amount)}</span> / 30.000.000 VND</strong></td>`;table_one+="</tr>";}}
if(data.game.active){for(let game of data.game.active){$(`button[data-game="${game}"]`).removeClass("hidden");}
$("div.play-rules").html(data.game.html);if(ag==""||ag==undefined){if(data.game.active.includes("chanle")){$(`button[data-game="chanle"]`).click();}else{$(`button[data-game="${data.game.active[0]}"]`).click();}}else{$(`button[data-game="${ag}"]`).click();}}
$("#momo-status").html(table_one);}}})}
loadSettings=()=>{initAjax({url:initUrl({type:"settings"}),method:"POST",success:function(data){if(data.status==true){settings=data;if(data.active==1){$("#author").html(`<a href="${data.href}" target="_blank">${data.author}</a>`);let html_contact="";for(let contact of data.contacts){html_contact+=`<p><a class="text-white" href="${contact.href}" target="_blank"><span class="btn btn-success text-uppercase">${contact.name}</span></a></p>`;}
$("#note").html(data.note);$("#note_modal").html(data.note);$("#noteModal").modal();$("#contact").html(html_contact);if(data.ads!==""&&data.ads!==undefined){$(".ads").removeClass("hidden").html(data.ads);}
if(data.notifications!==""&&data.notifications!==undefined){$(".notifications").removeClass("hidden").html(data.notifications);}
loadMomo();if(data.history=="1"){loadHistorys(data.only_win,data.limit);}
if(data.hu.active=="1"){loadHu();loadHistoryHu();$("#amount-hu").text(number_format(data.hu.amount));$("#roles-hu").text(data.hu.roles.join(", "));}
if(data.week_top){loadWeekTop();$(".week_top").removeClass("hidden");}
if(data.day_mission.active==1){loadDayMission(data.day_mission.cstmd_encode);}
var myVar=setInterval(myTimer,1000);}}}})};loadHistorys=(only_win,limit)=>{initAjax({url:initUrl({type:"history",only_win,limit}),method:"POST",success:function(data){if(data.status==true){if(data.history.status==true){let status_win={1:'<span class="label label-success text-uppercase">Tháº¯ng</span>',"-1":'<span class="label label-secondary text-uppercase">Thua</span>'}
let html_history="";for(let history of data.history.data){html_history+="<tr>";html_history+=`<td>${history.partnerId}</td>`;html_history+=`<td>${number_format(history.amount)}</td>`;html_history+=`<td><span class="fa-stack"><span class="fa fa-circle fa-stack-2x"></span><span class="fa-stack-1x text-white">${history.comment}</span></span></td>`;html_history+=`<td>${status_win[history.victory]}</td>`;html_history+="</tr>";}
$("#history").html(html_history);}}else{}}});};loadWeekTop=()=>{initAjax({url:initUrl({type:"week_top"}),method:"POST",success:function(data){if(data.status==true){if(data.data.status==true){let html_weektop="";for(const[key,value]of Object.entries(data.data.data)){html_weektop+='<tr>';html_weektop+=`<td><span class="fa-stack"> <span class="fa fa-circle fa-stack-2x text-danger"></span><strong class="fa-stack-1x text-white">${key}</strong></span></td>`;html_weektop+=`<td class="col-xs-2"><span class="label label-success">${value.partnerId}</span></td>`;html_weektop+=`<td class="col-xs-5 text-center"><span class="label label-danger">${number_format(value.result)}</span></td>`;html_weektop+=`<td class="col-xs-5 text-center"><span class="label label-danger">${number_format(data.data.gift[key])}</span></td>`;html_weektop+='</tr>';}
$(".week_top #week_top").html(html_weektop);}}}});};loadDayMission=(cstmd_encode)=>{initAjax({url:initUrl({type:"render_day_mission",cstmd_encode}),method:"POST",success:function(data){if(data.status==true){$("[data-minigame=day_mission]").removeClass("hidden");$(".minigame-rules").append(data.html);}}});}
loadHu=()=>{initAjax({url:initUrl({type:"balance-hu"}),method:"POST",success:function(data){if(data.status==true){$("#hu-left-display").removeClass("hidden");$(".hu-balance").html(number_format(data.amount));}}});}
check_dayMission=(partnerId)=>{initAjax({url:initUrl({type:"check-day-mission",partnerId}),method:"POST",beforeSend:function(){$(".check-day-mission").attr("disabled",true).addClass("disabled");$("#day_mission_querying").show();$("#query_done").html();$("#non_query").hide();},success:function(data){if(data.status==true){$("#query_done").html(data.html);$("#query_done").show();$("#day_mission_querying").hide();$(".check-day-mission").attr("disabled",false).removeClass("disabled");}else{alert(data.message);$("#non_query").show();$("#day_mission_querying").hide();$(".check-day-mission").attr("disabled",false).removeClass("disabled");}}})};reward_dayMission=(partnerId,milEncode)=>{initAjax({url:initUrl({type:"reward-day-mission",partnerId}),method:"POST",data:{milEncode},beforeSend:function(){$(".reward-day-mission").attr("disabled",true).addClass("disabled");},success:function(data){if(data.status==true){if(data.data.status==true){let data_response=data.data;$(".reward-day-mission").remove();$(".ntmsg").html(`
                            <div><b>${data_response.message}</b></div>
                            <div class="st"><b class="text-danger">Sá»‘ tiá»n: ${number_format(data_response.amount)} vnÄ‘</b></div>
                            <div class="st"><b class="text-warning">Lá»i nháº¯n: ${data_response.comment}</b></div>`);}}else{$(".ntmsg b").text(data.message).addClass("text-danger");}}})};checkTran=(tran_id)=>{initAjax({url:initUrl({type:"check-tran",tran_id}),method:"POST",beforeSend:function(){$(".check-tran").attr("disabled",true).addClass("disabled");},success:function(data){if(data.status==true){if(data.data.status==true){$("#result-check").attr("class","").addClass("alert alert-success").html(data.data.message);}else{$("#result-check").attr("class","").addClass("alert alert-danger").html(data.data.message);}}else{$("#result-check").attr("class","").addClass("alert alert-danger").html(data.message);}
$(".check-tran").attr("disabled",false).removeClass("disabled");}})};joinhu=function(partnerId){initAjax({url:initUrl({type:"join-hu",partnerId}),method:"POST",beforeSend:function(){$(".submit-join-hu").attr("disabled",true).addClass("disabled");},success:function(data){if(data.status==true){if(data.data.status==true){$("#msg_hu").html(data.data.message);$(".submit-join-hu").attr("disabled",false).removeClass("disabled");if(data.data.is_join==1){$(".submit-join-hu").removeClass("btn-success").addClass("btn-danger").html("Há»§y Tham Gia");}else{$(".submit-join-hu").removeClass("btn-danger").addClass("btn-success").html("Tham Gia");}}else{$("#msg_hu").html(data.data.message);$(".submit-join-hu").attr("disabled",false).removeClass("disabled");}}else{$("#msg_hu").html(data.data.message);$(".submit-join-hu").attr("disabled",false).removeClass("disabled");}}})}
loadHistoryHu=function(){initAjax({url:initUrl({type:"history-hu"}),method:"POST",success:function(data){if(data.status==true){$("#msg_history_hu").html(data.html);}else{console.log(data.message);}}})}
return{init:function(){loadSettings();},coppy:function(str){copyStringToClipboard(str);},play:function(str){window.open(`https://nhantien.momo.vn/${str}`,'_blank')},number_format:function(number){number_format(number);},check_tranid:function(){$this=this;let tranid=$("input[name=tran_id]").val();checkTran(tranid);},hu_click:function(){$("#hu-info").modal("show");},check_dayMission:function(){$this=this;let partnerId=$("input[name=partnerId]").val();check_dayMission(partnerId);},joinhu:function(){let partnerId=$("#result_hu input[name=partnerId]").val();joinhu(partnerId);},reward:function(){$this=this;let partnerId=$("input[name=partnerId]").val();let milEncode=$(".reward-day-mission").attr("data-mil-encode");reward_dayMission(partnerId,milEncode);}}}();"undefined"!=typeof module&&"undefined"!=typeof module.exports&&(module.exports=QuangApp),$(document).ready(function(){QuangApp.init()});function myTimer(){var d=new Date();var n=d.getSeconds();$(".coundown-time").text(60-n);if(n==0){if(settings.active==1){loadMomo(game_active);if(settings.history=="1"){loadHistorys(settings.only_win,settings.limit);}}}}
$("#result_hu [name=partnerId]").on("input",function(){if(this.value.length>=10&&this.value.length<=11){$("#msg_hu2").html('<button type="text" class="btn btn-success submit-join-hu" onclick="QuangApp.joinhu()">Tham gia</button>');}else{$("#msg_hu2").html("Vui lÃ²ng nháº­p sá»‘ Ä‘iá»‡n thoáº¡i Ä‘á»ƒ tiáº¿p tá»¥c");}});